version: '3.8'

services:
  visual-regression-tool:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: visual-regression-testing
    ports:
      - "${EXTERNAL_PORT:-80}:8501"  # Default to port 80, can be overridden
    volumes:
      - ./test_results:/app/test_results
      - ./logs:/app/logs
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Production nginx reverse proxy (for AWS/Digital Ocean)
  nginx:
    image: nginx:alpine
    container_name: visual-regression-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - visual-regression-tool
    restart: unless-stopped
    profiles:
      - production
